pysb/pysb

doc/conf.py

sphinx otherwise does not understand ..autosummary.
pysb/core.py:docstring of pysb.core.Observable:32: ERROR: Unknown directive type "autosummary".

Add sphinx.ext.autosummary to conf.py

---

pysb/core.py

Monomer.__init__ is the real issue here (the ComponentSet one is actually harmless in practice). I introduced this myself, 6 (!) years ago to the day, when PySB (and my Python experience) was about 1 month old. I'm actually surprised this hasn't bitten anyone already.

fix mutable default args on a couple of methods

---

pysb/integrate.py

Apparently " for array" was removed from the exception string
in the scipy version that I have.
(cleaned up from original @keszybz submission)

Fix exception detail in docstring

---

pysb/integrate.py
pysb/tests/jacobian_runtimes.py
pysb/tests/test_integrate.py

This feature uses Sympy to analytically calculate the Jacobian of the ODEs. Like the RHS function, the Jacobian is implemented as a callable that returns a matrix, and like the RHS it can also be inlined using scipy.weave. When the Jacobian is not explicitly supplied to the integrator (e.g., VODE), it is approximated by finite-differences calculations. Using the analytical Jacobian, inlined, results in small but consistent speedups for simulations of the EARM and Robertson models. Hopefully it will also help minimize convergence failures during parameter estimation runs!
More comments on specific changes can be found in the commit messages.

Calculate Jacobian of ODEs analytically and supply to integrator

---

pysb/core.py
pysb/generator/bng.py
pysb/integrate.py
pysb/tests/test_bng.py
pysb/tests/test_expressions.py
pysb/tests/test_integrate.py

This fixes issues #147 and #151. There were two problems: the first was that sympy_to_muparser in pysb.generator.bng was calling the str() function on Expression.expr directly, which works when the Expression is some kind of algebraic formula, but not when it's a single Parameter or Observable (because the Parameter/Observable's own repr method supersedes sympy.Symbol). To fix this I added a function that is explicitly for getting the string representation of the Expression formula.
The other problem was that the call to expand_expr(self.model).evalf(subs=subs) in integrate.py had a syntax error--the argument self.model was erroneous (issue #147). Also this call was using the wrong substitution dict--the substitution dict was keyed by parameter name, rather than by symbol (Parameter …

Fix expressions

---

pysb/integrate.py

Print the time at each step rather than just '\t'.

Fix verbose option in Solver.run

---

.travis.yml

miniconda.sh unpacks to ~/miniconda2 now which broke our travis setup. This explicitly tells it to use ~/miniconda again. I am self-:+1:'ing this one as it's pretty trivial and our travis integration is totally busted without it.

Fix miniconda prefix in travis config

---

pysb/bng.py

We were accidentally converting all factors from the "rate" in BNG net-file
reactions to sympy.Symbol, even the constant numeric scaling factors (2, 0.5,
etc). Somehow this all worked out properly in the end but it's certainly
better to convert the constants to sympy.numbers.Float instead.

Treat BNG symmetry/stoichiometry factors as numbers

---

pysb/macros.py

This has been supported internally for a while, but we forgot to update
the docs and parameter checks in the macro support code to match.

Allow Expressions in addition to Parameters in macro calls

---

pysb/bng.py
pysb/tests/test_bng.py

This PR improves BioNetGen temp file handling by securely creating a temporary directory for each interface instance to BNG with python's `tempfile.mkdtemp` (fixes #179). This required adding in an explicit `execute()` step to `BngFileInterface`, in order to allow the user to read in files within the interface's `with(...)` context before it exits, when cleanup (deleting the temp directory) is done.
As a side effect, this enables sequential sets of actions to be run in multiple `execute()` steps. Since network generation can be costly for large networks, I also added an `execute(reload_netfile=True)` option, which is useful for e.g. sequential simulations in BNG using the same reaction network (see the new unit test in pysb/tests/test_bng.py).

Improved BNG temp file handling & support for sequential BNG simulations

---

pysb/export/matlab.py

This wasn't updated when our internal species symbols gained the "__"
prefix, so the prefixes were left out of the regex that matches species
terms. The result was terms like "__y(0)" in the resulting matlab code
which is both incorrect (should be "y(0)") and also invalid matlab syntax
(no leading underscores on symbol names).
Closes #170.

Fix species name fixup in matlab exporter

---

.travis.yml
pysb/core.py
pysb/generator/bng.py
pysb/generator/kappa.py
pysb/kappa.py
pysb/tests/test_core.py
pysb/tests/test_kappa.py

This (long overdue) pull request is based off of @ryants branch (pull request #117) which added additional Kappa functionality, including ANY and WILD bonds and Expressions, and some new tests.
In addition to these changes, I updated kappa.py to use KaSa for all static analysis rather than complx, which is now deprecated. I also fixed what was previously the "sympy_to_muparser" function in the generator/kappa.py file to make it match our current approach in generator/bng.py.
One thing to note is that Kappa 4.0, which is currently under development, will use a different syntax for observables. I updated the necessary code in 828492259e14f but then commented it out in 6204902 because this new syntax causes problems for some versions of KaSim3. When KaSim 4.0 is stable, we can uncomment …

Kappa updates (ANY/WILD, Expressions, KaSa, tests)

---

pysb/bng.py
pysb/generator/bng.py

Two minor fixes to the BioNetGen language outputted by PySB:
* Wrap model declarations with `begin model` and `end model`
* Only send `done` command when using the BNG console (not needed for file-based BNG interface)

BNGL fixes: begin/end model declarations; only send "done" when using console

---

.travis.yml
pysb/bng.py
pysb/generator/bng.py

The Kappa team are making lots of updates recently, leaving us with a moving target for Travis unit tests. For now, we'll stick to the commit from March 9, 2016: https://github.com/Kappa-Dev/KaSim/commit/f87eada74a188dc14eabfbe43f8e264cd5352a6a until a more permanent solution is found.

Use fixed git SHA for Kappa tests in Travis

---

pysb/integrate.py
pysb/simulate.py
pysb/tests/test_integrate.py

Rebased version of #192 from @JamesPino. Original comment:
> Corrected an lsoda error that occured if _use_analytic_jacobian was False. Before it would try to assign self.jac_fn = lambda t, y, p: jacobian(y, t, p). But jacobian is only defined if _use_analytic_jacobian =True.
> 
> The rest are enhancments to the simulator class. A lot of calls could be done once outside of the main loop, which sped up the _calc_yobs_yexp quite a bit.
This still ought to have a test that would fail before the jac_fn fix. Will implement that now.

Simulator fixes

---

.travis.yml
pysb/kappa.py

This pull request is modeled after the approach to finding the path to the BNG executable with a couple of modifications. In particular, while it assumes that the KaSim and KaSa executables are in the same directory, if the user sets the kappa path using set_kappa_path it errors if KaSim is not found in the given directory but only warns if KaSa is not found. This is because KaSa is not actually included with the (current) Kappa binary downloads, so we don't want to prevent people from running KaSim just because they haven't built KaSa.
If the user sets the path to Kappa using the KAPPAPATH environment variable, KaSim and KaSa are expected to both reside in that location, but if KaSa is missing the code only errors if the user attempts to run one of the static analysis functions …

Kappa path environment variables and directory search

---

pysb/export/pysb_flat.py

This is needed by some models, including certain versions of EARM, as requested by @JamesPino.

Add MatchOnce to pysb_flat exporter

---

pysb/kappa.py

If model.name is None then os.path.join will fail. Wrapping in str()
fixes this problem.

Wrap model.name with str() in case it is None

---

pysb/testing/__init__.py

If the SelfExporter has been turned off, calling with_model won't allow
access to the components when writing tests. This commit saves and then
restores the state of the SelfExporter after the with_model decorator
runs so that components can be referred to as globals within testing
functions without affecting global SelfExporter state.

Reset SelfExporter state after calling with_model

---

pysb/core.py
pysb/tests/test_core.py

There were a few places in core where sites and states of monomers were checked for validity by checking to see if they are strings with `type(s) == str`. However, in my calling code (which I am rewriting to use a Unicode sandwich and be Python 3 compatible) I am passing in Monomer definitions with unicode definitions. This works for Python 3,  in which unicode strings are `str`, but in Python 2, these `type(s) == str` checks fail.
In the update to make pysb Python 3 compatible, core.py already switches to `basestring` checks in most places, with `basestring = str` added so that there is no NameError in Python 3. But these `str` checks have persisted.
In this PR I've updated the checks in the various places to use `isinstance(s, basestring)` instead of `type(s) == str`. I've also moved to …

Replace type(s) == str with isinstance(s, basestring)

---

pysb/kappa.py
pysb/tests/test_kappa.py

Kappa unit tests sometimes fail due to #211 - `test_flux_map()` assertion `ok_(len(simdata['time']) == 101)` fails randomly. The `simdata['time']` array seems to sometimes be a different length depending on kappa's RNG seed, e.g. it works if the seed is `123456` but fails if the seed is `123`; the latter seed means that `len(simdata['time']) == 102`, not `101`. Perhaps this is a bug that should reported to kappa devs?
This PR sets the kappa seed in the unit tests to a fixed value `_KAPPA_SEED=123456` which makes our unit tests pass deterministically. Try changing the seed value to `123` to reproduce the error (perhaps someone with more kappa knowledge than me could work out the root cause?)

Deterministic kappa tests using fixed seed for KaSim

---

pysb/bng.py
pysb/generator/bng.py
pysb/generator/kappa.py
pysb/tests/test_bng.py
pysb/tests/test_kappa.py
pysb/tools/render_species.py

This is a follow-up to the previous PR (#230) which made the corresponding fix in core.py, and fixes issue #233. We had found that while #230 allowed models to be created with unicode names/sites in Python 2, BNG and Kappa generation would fail due to unicode strings not being matched in the series of tests on site conditions. I've added corresponding tests in test_bng.py and test_kappa.py.
In the interest of completeness, I grepped all PySB source for other code containing `type(foo) == str` or `isinstance(foo, str)` and found cases only in bng.py and (_bng_param method) and render_reactions.py, which I also updated in this pull request.

Fix isinstance(foo, str) in bng and kappa generation

---

pysb/export/sbml.py

The SBML exporter makes some assumptions about how PySB names species,
and this changed in the BNG interface code which creates the species
but wasn't updated to match here.

Fix SBML export species id mismatch with leading underscores

---

pysb/bng.py
pysb/examples/michment.py
pysb/examples/run_michment.py
pysb/examples/run_tyson_oscillator.py
pysb/examples/tyson_oscillator.py
pysb/integrate.py
pysb/logging.py
pysb/simulator/base.py
pysb/simulator/scipyode.py
pysb/tests/__init__.py
pysb/tests/test_integrate.py
pysb/tests/test_simulationresult.py
pysb/tests/test_simulator_scipy.py

This PR contains two main features:
* A new logging framework for PySB, built on the Python logging module, just integrated into the Simulation class for now, but which will facilitate new capabilities:
* Finer-grained verbosity selection than verbose=True or False using logging levels.
* Support for multiple logging handlers, allowing logging to console, file, various centralized network servers. This will be useful for distributed/parallel/cluster-based PySB setups.
* We've discussed a benchmark suite before. A custom benchmarking log handler could be written to time various pieces of code based on start/stop events.
* The ability to run simulations using multiple different initial condition/parameter value sets. This code was written by @lh64. This capability is also important for the …

Logging framework & Simulator class multiple initials/params support

---

pysb/core.py
pysb/importers/bngl.py

Two small fixes:
* Updated ComplexPattern docstring to show Compartment can be `None` (otherwise a warning is generated in some IDEs)
* `match_once` should be a boolean in the BNGL importer, not int.

Two small fixes for data types not matching docstrings

---

pysb/bng.py
pysb/importers/sbml.py
pysb/kappa.py
pysb/pathfinder.py
pysb/tests/test_importers.py

Since we're adding more links to external executables from PySB (e.g. cupSODA), it makes sense to centralise the code used for getting and setting paths to those executables from default paths and/or environment variables.
This PR adds a small PySB submodule called pathfinder to handle this task.

Centralised methods for getting and settings paths to external executables

---

pysb/bng.py
pysb/importers/bngl.py
pysb/tests/test_bng.py
pysb/tests/test_importers.py

This PR adds Windows support for the BNGL and SBML importers, and fixes the unit test suite on that platform. This was done by switching the `BngConsole` calls, which don't work on Windows due to a lack of `pexpect.spawn()` support, to `BngFileInterface`.

Fix BNGL, SBML importers and unit tests on Windows

---

pysb/simulator/base.py
pysb/tests/test_simulator_scipy.py

Due to a numpy issue, unicode Observable and Expression names (even if they are ASCII encodeable) in python 2 error when creating the output arrays of simulation in `pysb.simulator.base`. This pull request adds a function to test for numpy.ndarray with unicode explicitly (rather than testing for python version) and if it is not allowed in the current environment, the Observable and Expression names are ascii-encoded. In case a UnicodeEncodingError is encountered in this process, it is raised.

Handling unicode Observable and Expression names in python 2

---

pysb/importers/bngl.py
pysb/importers/sbml.py
pysb/logging.py
pysb/simulator/base.py

A small commit which improves the BNGL and SBML importer expression handling, allowing parameters, observables and other expressions as symbols within an expression.
I've also added a convenience function `model_from_biomodels` which downloads an SBML model from [BioModels](https://www.ebi.ac.uk/biomodels-main/) and runs it through the SBML translator in a one-liner (see example doctest).

Import from BioModels; better SBML expression handling

---

doc/conf.py
pysb/simulator/base.py

sympy.lambdify is relatively slow, and was unnecessarily being evaluated for
every simulation during `SimulationResult` construction. I've refactored the
`SimulationResult` constructor so that each expression is only lamdbified
once, which greatly increases speed. On my laptop, running 25 simulations
with a 202 expression model, the total time went from >12 minutes to
<12 seconds.
Also included is a one line fix for the broken [`pysb.simulator` readthedocs module](http://pysb.readthedocs.io/en/latest/modules/simulator.html) (empty at the time of writing).

Much faster expression evaluation by pulling lambdify out of loop

---

pysb/simulator/cupsoda.py

The current unit test suite for the cupSODA interface fails on Python 3.
This commit has a few small changes to add Python 3 compatibility and
fix the unit test suite.

Add python3 support to cupSODA simulator

---

doc/modules/importers/index.rst
pysb/bng.py
pysb/simulator/cupsoda.py
pysb/tests/test_bng.py

Defining a parameter or expression using a sympy function name (e.g.
`deg`) will cause the following error:
SympifyError: SympifyError: <function deg at 0x10f0d0140>
The error is down to `_parse_reaction` in bng.py, which runs `sympy.S(x)`
where `x` is a string such as `'deg'`. Converting the string to the relevant
parameter or expression object resolves this.
Resolves: pysb/pysb#259

Allow rxn rate params/exprs with sympy fn names

---

pysb/core.py
pysb/tests/test_core.py

The PysbFlatExporter fails with compartmental models due to `Compartment`'s
`repr()` implementation, which means parameters and parent compartments
get printed in full rather than just their name, which leads to a
`ComponentDuplicateNameError` with compartmental models when using the
PysbFlatExporter. This PR fixes the issue.
Resolves: pysb/pysb#210

Fix PysbFlatExporter with compartmental models

---

pysb/simulator/base.py
pysb/tests/test_simulator_scipy.py

This PR fixes two bugs: setting param_values which underlie initial conditions without setting the initials argument silently fails on repeat simulations (pysb/pysb#252) and setting initial conditions to zero will silently be ignored (pysb/pysb#251).
Resolves: #251, #252

Fix silent errors with simulation params/initials

---

.travis.yml
doc/index.rst
doc/tutorial.rst
pysb/kappa.py
pysb/pathfinder.py
pysb/tests/test_kappa.py

This PR introduces updates to the Kappa (KaSim and KaSa) interface in PySB to make simulations and static analysis (generating contact maps and influence maps) compatible with the 4th generation Kappa tools. 
- The executable for static analysis changed from KaSim to KaSa
- The output folders for contact map and influence map have to be specified separately
- The parameterization of KaSim changed, most importantly with respect to specifying the number of time points to simulate vs intervals between returned samples (the -p option of KaSim)
- The output format of KaSim changed and this required changes in reading in the results
- The prerequisites of compiling Kappa changed and these are updated in the Travis config
Note that KaSim doesn't produce an output file if no Observables are …

Kappa4 interface fixes

---

pysb/kappa.py
pysb/tests/test_kappa.py

The newer versions of Kappa produce files in the current working
directory (`input.ka` and so on, and an `output` directory),
which leaves cruft after running unit tests. I've set Kappa's working 
directory to the `base_directory`.
Also, a file handle was opened in` _parse_kasim_outfile` but not closed.
This is fixed.

Kappa tests use temp dir, fix unclosed file

---

pysb/bng.py
pysb/tests/test_bng.py

Modified pysb.bng.BngBaseInterface.read_simulation_results() to read in header names from the .gdat file rather than set the names equal to the names of model.observables. This is necessary because BNG can be instructed to print function (Expression) values to the .gdat file with the 'print_functions=1' argument. This also required changing the 'if' statement from a check on whether model.observables exists to whether the .gdat file exists (since, in principle, the .gdat file could contain only functions).

Read Expression values from BNG .gdat files

---

pysb/core.py
pysb/export/stochkit.py
pysb/simulator/scipyode.py
pysb/simulator/stochkit.py
pysb/tests/test_simulator_stochkit.py

* Enable simulation of models with expressions on the `StochKitSimulator` class
* Add an `expand_observables` argument to `Expression.expand_expr()`, which expands Observables into species, reducing code duplication
* The `StochKitExporter` is now much faster for large models
* Reactions which are mass action according to the StochKit definition are now exported as mass action in the StochKit XML. This means that custom propensity functions don't have to be compiled for these reactions, reducing StochKit compile time for large models. It also means that mass action only models can be run using the Windows StochKit Lite, which doesn't have custom propensity function (non mass action) capability.

Fix StochKitSimulator for models w/ expressions

---

.travis.yml
doc/examples/robertson_standalone.py
pysb/export/python.py
pysb/generator/bng.py
pysb/integrate.py
pysb/simulator/scipyode.py
pysb/tests/test_expressions.py
pysb/tests/test_simulator_scipy.py
setup.py

This PR replaces the previous `eval` mechanism for ODE evaluation in `ScipyOdeSimulator` with `lambdify`, allowing some extra rate laws which would previously fail, e.g. `Piecewise` expressions (see new unit test `test_piecewise_expression`). It is >30% faster on the time_scipy_lsoda benchmark for me vs current master (553eadc).
Experimental [theano](http://deeplearning.net/software/theano/) support is also added, and can be enabled using a `use_theano=True` argument to the `ScipyOdeSimulator` constructor. Theano has some interesting capabilities like GPU offloading which might help with large, complex expression sets, but it needs more testing and benchmarking to establish which simulation scenarios it's appropriate for.
The PR also slightly cleans up the BNG generator code by …

ScipyOdeSimulator lambdify and theano support

---

pysb/simulator/base.py
pysb/tests/test_simulator_scipy.py

This patch fixes `SimulationResult.all` when any observable or expression has a unicode name, and amends the unit tests to check `.all` works.
Fixes #290

Fix SimulationResult.all with unicode obs/exprs

---

appveyor.yml
pysb/pathfinder.py
pysb/simulator/base.py
pysb/tests/test_bng.py
pysb/tests/test_kappa.py

This PR adds continuous integration on Windows using the [Appveyor](https://ci.appveyor.com/) platform. Enable using the Appveyor Github integration.
Notes:
- I've set up tests for Python 2.7 and Python 3.4 on win32 platform
- PyGraphviz binaries from [Chris Gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs/) are used, but can't be downloaded directly, so I used Dropbox. The files are <1Mb so performance shouldn't be impacted.
- Kappa doesn't have a `KaSa` binary available for Windows AFAIK, so the Kappa static analysis tests are skipped on that platform (Kappa simulations are still tested)
- Anaconda doesn't have a numpy 1.12 binary for Python 3.4/win32. I added doctest skip declarations to two tests in simulator/base.by to make the test suite pass on numpy 1.11.

Continuous integration on Windows (appveyor)

---

appveyor.yml
pysb/simulator/stochkit.py

Two small changes to get appveyor build working:
* Add theano to `conda install` list
* Skip a StochKit doctest which gives different output on Windows to Linux despite having the same seed (presumably due to random number generator differences)

Small fixes for Windows appveyor build

---

doc/conf.py

Small fix to get sphinx build working by adding `scipy.sparse` as mock module

Fix sphinx build by adding scipy.sparse mock module

---

.travis.yml
appveyor.yml

The download links for pygraphviz were broken due to the discontinuation of public Dropbox folders, and the link for BioNetGen was updated on the remote server to point to a newer version than desired for PySB (2.3.0 vs 2.2.6). These links have been updated to fix our appveyor continuous integration.

Fix link rot in appveyor config

---

pysb/tools/sensitivity_analysis.py

MPL 2.1's `boxplot` function now checks the dimensionality
of the array passed to it, so we need to `flatten` the entries
with numpy to make it compatible.

Sensitivity analysis code fix for matplotlib 2.1

---

pysb/simulator/scipyode.py

Weave uses shelve and bsddb to cache compiled object code, with the C code
string itself as the key. bsddb only accepts str and int keys, but in some
cases when PySB model components have unicode names the C code ends up as
unicode after the various string templating operations used to build the
code. The final C code shouldn't contain actual component names after the
complete transformation, so it should always be safe to coerce the code to
str before handing it off to weave.

Ensure C code passed to weave is str, not unicode

---

pysb/integrate.py
pysb/simulator/scipyode.py

Our logging framework now controls the various output produced by weave.inline
and the C compiler. Due to some misbehavior within distutils, we need to
dynamically monkey-patch its internal logging framework to achieve this.
C compiler warning messages now become visible at log level DEBUG.
Due to these changes, the nose setup_module function in pysb.integrate is no
longer needed and has been removed.
Also an unrelated bug in ScipyOdeSimulator's Jacobian calculation was fixed.

Improve control over weave.inline console output

---

pysb/core.py
pysb/simulator/base.py
pysb/simulator/bng.py
pysb/simulator/cupsoda.py
pysb/simulator/scipyode.py
pysb/simulator/stochkit.py
pysb/tests/test_simulationresult.py
setup.py

This PR implements `SimulationResult.save()` and `.load()` functions, using an HDF5-based file format. HDF5 is a hierarchical, binary storage format well suited to storing matrix-like data. This implementation uses the h5py package.
The file format stores not only the simulation trajectories, but also metadata relevant to archiving, such as the model itself, simulation settings, parameter and initial condition values, simulation date/time, and PySB version.
The goals are to aid reproducibility and to facilitate exchange of simulation data.

Save and load SimulationResults to HDF5 files

---

doc/modules/index.rst
doc/modules/modeltests.rst
doc/modules/pattern.rst
pysb/core.py
pysb/pattern.py
pysb/testing/modeltests.py
pysb/tests/test_core.py
pysb/tests/test_pattern.py
setup.py

Add a pattern matching engine (pattern.py) and a model test suite built off of that engine (testing/modeltests.py).
The pattern engine uses a graph-based implementation with networkx for checking pattern isomorphism. It can do one off matching (`SimplePatternMatcher` class) or repeated lookups (`SpeciesPatternMatcher`, `ReactionPatternMatcher` and `RulePatternMatcher`) which create lookup caches for fast repeated pattern matching. See the docstring examples in those classes for details. The framework is designed for large numbers of tests against a fixed list of species/reactions/rules (typically, those from a single model). Thus, the functions typically try to "fail fast" (i.e. reject putative matches quickly, where possible, by performing computationally simpler checks first).
The core …

Pattern matcher and model test suite

---

appveyor.yml

Our Appveyor Python 3.4 builds are currently failing.
The build was using mkl=2017.0.4, which was erroring with "DLL
load failed" as described here:
https://github.com/numpy/numpy/issues/9933
For the time being we can get our Appveyor build working again
by pinning mkl to 2017.0.3. Hopefully upstream will fix soon.
Edit: Also updated the graphviz download URL, since the old one stopped working today

Pin mkl to fix Appveyor Python 3.4 builds

---

pysb/core.py
pysb/tests/test_core.py

This should (and now does) raise a `DuplicateMonomerError`
Fixes: #183

Fix ComplexPattern.__call__ for duplicate monomers

---

pysb/simulator/base.py
pysb/simulator/bng.py
pysb/simulator/scipyode.py
pysb/simulator/stochkit.py
pysb/tests/test_simulator_scipy.py

Previously, tspan, initials, and param_values supplied to
Simulator.run() calls persisted to future run calls, which seems
unintuitive. This commit makes these arguments persist only for the
duration of the run() call. It also refactors some of the more
convoluted logic for setting initials/param_values and adds a few
unit tests.
Fixes: #267

Unpersist Simulator.run() arguments

---

pysb/core.py
pysb/tests/test_core.py

`MonomerPattern.__init__` should verify that any strings (states) given
in site_conditions are allowable for that monomer. E.g. for this
Monomer:
Monomer('A', ['x'], {'x': ['spam', 'eggs']})
This now raises an exception:
A(x='foo')
Fixes: #90

Verify site states in MonomerPatterns

---

pysb/core.py
pysb/generator/bng.py
pysb/tests/test_bng.py

This PR fixes `Rule.is_synth()` and `Rule.is_deg()` for reversible
synth/deg rules of the form
Rule('synth_deg', None <> A(), k_synth, k_deg)

Fix reversible synth/deg rules

---

pysb/core.py
pysb/jacobian.py
pysb/macros.py
pysb/pattern.py
pysb/simulator/base.py
pysb/simulator/stochkit.py
pysb/tests/test_bng.py
setup.py

This PR fixes some Python 2/3 compatibility problems in an attempt to solve #271. Note that currently
- The `pysb.macros.assemble_chain_sequential_base` doctest is failing in Python 3
- The `pysb.macros.chain_species_base` doctest is failing in Python 3
these will need to be diagnosed and fixed before merging.
I found that the 2to3 issue mentioned in #271 was due to setup.py, where ```
cmdclass.update(versioneer.get_cmdclass())``` overwrote the `build_py` entry of `cmdclass` causing _all_ 2to3 fixes to be applied. This PR first gets the versioneer cmdclasses and then overwrites the `build_py` entry with the custom `build_py` class defined in setup.py. This fixes the issue with 2to3 but might have side effects relevant to versioning that I am not aware of.

Fix some Python 2/3 compatibility issues

---

pysb/core.py
pysb/macros.py
pysb/pattern.py
pysb/tests/test_core.py
pysb/tests/test_kappa.py

A dangling bond is when a specified bond has no binding partner, e.g.
```python
A(a=None) % A(a=1)
```
Patterns with dangling bonds are disallowed in Kappa and pending deprecation in BioNetGen. This PR adds dangling bond detection when `ReactionPattern` patterns, allowing users to detect these mistakes early (before network generation).

Dangling bond detection for ReactionPattern

---

.travis.yml
appveyor.yml
pysb/integrate.py
pysb/kappa.py
pysb/simulator/base.py
pysb/simulator/scipyode.py
pysb/simulator/stochkit.py
pysb/tests/test_kappa.py
pysb/tools/render_reactions.py
pysb/tools/render_species.py
pysb/tools/species_graph.py
pysb/util.py

* pygraphviz support is now optional (tests complete without it):
pydot is now an alternative for reading .dot (graphviz) files. 
pygraphviz support on Windows on recent versions of Python is
patchy at best - pydot supports more platforms and is easier to
install.
* When dot file reading is required (kappa interface), the results are
now returned in the (more flexible and maintained) networkx format.
The dot file itself can be read using pydot or pygraphviz (both are
tried by default) - see new pysb.util.read_dot() function. Networkx
can export back to pygraphviz if required, as updated docs show.
* Move Python 3 continuous integration on both travis and 
appveyor to Python 3.6, to standardise across platforms
* Update doctests to numpy 1.14 standard (no leading whitespace
inside bracket …

networkx/pydot support for reading .dot files

---

.travis.yml
appveyor.yml
pysb/simulator/scipyode.py
pysb/tests/test_simulator_scipy.py
setup.py

Adds Cython support to ScipyOdeSimulator. This is useful because our
current ODE compilation backend (weave) does not support Python 3;
Cython does.
The ODE compilation system backend can be specified by a new
`eqn_mode` argument: `cython`, `weave`, `theano` or `python`.
If left as None (default), the system will try to use `weave`,
then `cython`, then `python`.
If the auto-detect falls back on `python` mode, a warning is shown
that the simulation may be slow, and recommends the user install
`cython` or `weave`.

Cython support for ScipyOdeSimulator

---

.travis.yml
appveyor.yml
pysb/core.py
pysb/generator/bng.py
pysb/generator/kappa.py
pysb/kappa.py
pysb/macros.py
pysb/tests/test_bng.py
pysb/tests/test_kappa.py

This PR introduces support for Kappa 4, which is enabled by default.
To use Kappa 3 syntax, use the `pre4syntax=False` argument to
`run_simulation` or `run_static_analysis`. Note that Kappa now
requires agents on the reactant side to correspond to agents on the
product side of a rule (i.e. order is preserved). The "dot" agent
is implemented in PySB as `KappaDot`, and is necessary in
[certain situations documented in the Kappa Manual](https://github.com/Kappa-Dev/KaSim/blob/master/CHANGES.md#agent-order-in-rules-must-be-maintained).
For example, the following Kappa rule:
// Agent A spawns a copy of agent B
A(),. -> A(),B() @ 'r'
would be implemented in PySB as:
Rule('spawnB', A() + KappaDot() >> A() + B(), r)
This PR also improves Expression support for Kappa, implementing
`log`, `exp`, …

Kappa 4 support, expression improvements

---

.travis.yml
appveyor.yml
pysb/importers/sbml.py
pysb/integrate.py
pysb/pathfinder.py
pysb/simulator/scipyode.py
pysb/tests/test_importers.py
pysb/tests/test_simulator_scipy.py
pysb/tools/sensitivity_analysis.py

* Use pre-built binaries for bionetgen (+ nfsim and atomizer), kappa and stochkit. This reduces build time and hopefully improves reproducibility.
* Use 64 bit builds on appveyor (test on 64 bit across platforms)
* Fix Cython exception triggering by capitalizing the "Cython" import
* Ensure weave is tested on Python 2.7
* Fix integrator doctests on Python 2.7 Win64 (calling numpy `.shape` shows integers as longs, with "L" suffix)

Use more anaconda binaries on CI builds

---

pysb/core.py
pysb/tests/test_kappa.py

In Kappa 4, a Ghost agent (placeholder 'dot') must be used to make
the two sides of a reaction rule match. For example, the following
two agent synthesis rule:
Rule('synthesize_A_and_B', M() + None + None >> M() + A() + B(), k)
This was previously failing (one None was silently dropped). This
has been fixed by modifying ReactionPattern.__add__ and implementing
__radd__. The only caveat is with multiple leading Nones, which will
need to be in parentheses to avoid a TypeError from adding two Nones:
None + (None + M())
This should also be avoidable by reordering the agents to put the
Nones last, as in the original example.
Fixes: #338

Fix Kappa 4 multiple agent synthesis

---

pysb/core.py

PySB v1.6.0 was just released, with the <> reversible rule operator
issuing a PendingDeprecationWarning. This commit changes that to a
DeprecationWarning, which should be included in the next release.

Deprecate <> operator for reversible rules

---

pysb/generator/kappa.py
pysb/tests/test_kappa.py

The kappa generator was incorrectly substituting parameter names in
expressions if one parameter was a substring of the other. This PR
uses the sympy printer instead of string replacement.
Fixes: #345

Fix kappa generator using certain expressions

---

pysb/core.py
pysb/importers/bngl.py
pysb/tests/test_core.py

The BNGL and SBML importers were creating Expressions from ints and
floats, which are better represented as Parameters. This PR
performs this conversion within the importers where applicable.
Fixes: #349

Expressions must be created from sympy.Expr

---

doc/installation.rst

Now that PySB and its dependencies including BioNetGen are on
Anaconda, the installation procedure is much simpler.
I've also added Cython to the list of recommended packages.

Simplify installation instructions

---

pysb/simulator/scipyode.py

If Cython or weave cannot find a working compiler on Windows, one
error than can occur is `ValueError: Symbol table not found`, generated
by numpy/distutils/mingw32ccompiler.py. This commit catches this
error and treats the compiler as non-functional, logging the occurence
as a DEBUG log message.

Catch Cython/weave compiler error on Windows

---

pysb/core.py
pysb/tests/test_core.py

This PR introduces a check at rule instantiation that every
product is concrete for synthesis rules.

Enforce synthesis products to be concrete

---

pysb/core.py
pysb/pattern.py
pysb/tests/test_core.py

A state, as opposed to a bond, should not be able to be defined as
None. Doing so causes an error in BNG: "reaction list cannot be read
because of errors". This commit adds a check for this condition
and a unit test.

Forbid defining a state as None

---

pysb/core.py
pysb/tests/test_core.py

None should be allowed in MonomerPatterns, to allow for models like
the following:
Monomer('A', ['phospho'], {'phospho': ['u', 'p']})
A(phospho=None) + A(phospho=None) >> A(phospho=1) % A(phospho=1)
#348 missed the mark somewhat... my intention was to disallow undefined
states in *species*, not in *patterns*. Such patterns are already detected 
as un-concrete, so they are forbidden in initials.
Thanks to @bgyori for spotting and reporting this.

Allow state=None in rule patterns

---

Dockerfile
doc/installation.rst

The Docker container now uses conda to install PySB, same as the non-Docker instructions.
Fixes: #358

Update Dockerfile and related instructions

---

pysb/export/__init__.py
pysb/export/mathematica.py
pysb/export/matlab.py
pysb/export/potterswheel.py
pysb/export/python.py
pysb/export/sbml.py
pysb/export/stochkit.py
pysb/generator/kappa.py
pysb/tests/test_exporters.py

This PR tests all PySB example models against all the available
exporters. It's heavily based on @keszybz's approach in #113.
I've also implemented explicit ExpressionsNotSupported and
CompartmentsNotSupported exceptions for the exporters which
don't support those features.
Fixes: #154
Fixes: #73

Tests for PySB exporters

---

pysb/bng.py

BNG errors and warnings often given line numbers referring to the BNGL
file. This PR adds line numbers to the BNGL output shown in PySB's
DEBUG log.

BNGL line numbers in PySB log

---

.travis.yml
appveyor.yml
pysb/core.py
pysb/export/sbml.py
pysb/tests/test_exporters.py
setup.py

This replaces the original SBML exporter with a libsbml-based one.
New features include compartment and expression support, and
conversion between SBML levels/versions (L3V2 by default).
Fixes: #269

LibSBML model exporter

---

pysb/core.py

Add some blank lines in Sphinx documentation, to generate code blocks properly.

Fix core documentation: add necessary whitespace

---

pysb/export/sbml.py
pysb/tests/test_exporters.py

As SBML does not provide any official support for "observables", I have here implemented the SBML export as AssignmentRule to a parameter.

add observables to sbml export

---

pysb/generator/bng.py
pysb/tests/test_bng.py

Support for exporting `e` and `pi` constants, and `&`, `|`, `Abs`, `Min`, `Max`, `Ceiling`, `Floor` functions to BioNetGen.

Additonal function support when exporting to BNG

---

pysb/core.py

`__getstate__` should not error if `.model` is not set

fix serialization of Components that do not have a model weakref set

---

pysb/core.py

The module/function name is captured by PySB when Components
are defined, but in some interpreters the `__name__` attribute
is not set for interactive sessions. To avoid an error, this
introduces a default value of `__unnamed__`.

Default module name when __name__ not set

---

pysb/export/stochkit.py

This previously failed because `lxml` outputs `bytes`, which
needs conversion into a UTF-8 `str` on Python 3.
Thanks to @ortega2247 for the report.

Fix StochKit export on Python 3 with lxml installed

---

pysb/simulator/base.py
pysb/tests/test_simulator_scipy.py

The `Simulator` class method `initials_dict` returns initial conditions
as a dictionary, mostly for use by network-free simulators like NFsim.
When initial conditions are set by an array or a list, species which
were not explicitly set using `Initial()` in the model are ignored.
This only affects users of the `BngSimulator`, which uses this
method, or anyone who called this method directly after setting
initials with an array or list.
This PR fixes the issue by returning a dictionary with values from the
array. This requires a species list for the model, so a `ValueError`
is raised where this is not available/`generate_equations` hasn't been
called yet.
Fixes: #376

Fix Simulator initials_dict when set by array

---

pysb/core.py

Implement `ComponentSet.__dir__()`, which enables tab completion of
component names at an IPython prompt and in Jupyter Notebook.

Tab completion of components in IPython, Notebook

---

pysb/simulator/scipyode.py
pysb/tests/test_simulator_scipy.py

Previously, unrecognised kwargs would be silently ignored. Now a
ValueError is raised if they are not recognised.

Validate init kwargs to ScipyOdeSimulator

---

pysb/simulator/stochkit.py
pysb/tests/test_simulator_stochkit.py

Previously, unrecognised kwargs would be silently ignored. Now a
ValueError is raised if they are not recognised.

Validate init kwargs to StochkitSimulator

---

pysb/simulator/cupsoda.py
pysb/tests/test_simulator_cupsoda.py

Previously, unrecognised kwargs and integrator options were
silently ignored. Now a ValueError is raised if they are not
recognised.

Validate cupsoda init kwargs and integrator opts

---

pysb/simulator/bng.py

The cleanup flag in BngSimulator's `__init__()` was being ignored;
only the value specified to `run()` was used. The `__init__()`
cleanup flag is now treated as a default, which can be overridden
on a per simulation basis in `run()` if required.

BngSimulator: respect cleanup flag in `__init__`

---

.travis.yml

Travis is failing due to the lack of anaconda binaries for python-libsbml on Python 3.7. I've added a temporary fix to install python-libsbml using pip, which compiles from source (slow). This can be switched back when/if the libsbml team releases an appropriate binary (I've requested one on the llibsbml-interoperability mailing list).

Fix Python 3.7 libsbml install on travis

---

setup.py

This PR fixes the package name that libsbml is available with on PyPI.

Fix package name for libsbml

---

pysb/pathfinder.py

Path detection in Anaconda was broken when they released
Python 3.7.1, due to a change in the version string. This
update no longer checks for an Anaconda environment
explicity, it goes straight to validating the paths
("it's easier to ask for forgiveness than for permission")
Fixes: #393

Fix path detection in Anaconda

---

pysb/pathfinder.py

This PR allows PySB to search paths defined in the system PATH variable for external executables. Paths in PATH have the lowest order of precedence (below specific environment variables, anaconda environments, and pathfinder's system default paths), so existing installations shouldn't be impacted.

Use system PATH variable in pathfinder

---

setup.py

#367 added `roadrunner` to `tests_require`, but the correct distribution name is `libroadrunner`. There *is* a `roadrunner` but it's something else. Travis wouldn't catch this because there's an explicit `pip install` for it. This PR fixes the distribution name.

Fix distribution name for libroadrunner

---

pysb/tests/test_simulationresult.py

Prevent model name from being permanently changed

---

pysb/simulator/cupsoda.py

cupSODA doesn't quote paths, which is problematic when a model
name includes e.g. spaces. The path is now sanitized to replace
non-alphanumeric characters with an underscore.
Fixes: #397

Remove non-alphanumeric characters from cupSODA model path

---

benchmarks/simulator.py
pysb/simulator/scipyode.py

I created a PR for Cython (https://github.com/cython/cython/pull/2595)
which added compiler directive support for cython.inline(), which
is now present in Cython>=0.92
This PR introduces user-configurable Cython compiler directives
within the ScipyOdeSimulator. By default, these directives disable
bounds, wrap around, "None", and initialized checks. Some initial
benchmarking on asv shows a speed improvement of about 5% on my
laptop (every little helps?)

Cython compiler directives for faster simulations

---

pysb/core.py
pysb/tests/test_core.py

`sympy.symbols(',')` throws a `ValueError`

fix exception when calling expand_obs() on Observable with no coeffs

---

pysb/export/stochkit.py

Raw numeric intial conditions, as opposed to those wrapped in a
parameter or constant expression, are not allowed in PySB.
This removes a superfluous check for this condition in the
StochKit exporter.

Remove stochkit initial condition support for numeric ICs

---

pysb/simulator/scipyode.py

On Windows, a lack of a functional compiler for Cython is often met with
the message "Unable to find vcvarsall.bat", which is cryptic for newbies.
This update adds a more descriptive warning complete with URL, logging,
and a consolidated "catch" condition.

Improve non-functional Cython error messages

---

pysb/simulator/base.py
pysb/tests/test_simulator_scipy.py

Add support for supplying simulation initial conditions and parameter
values as pandas DataFrames. Previously this was handled by implict
conversion to numpy array, which might lose the column order (i.e.,
initials species or parameters get swapped).
Implicit conversion or simulation initials or param values from anything
other than a list is now disabled, meaning that users must now supply
a DataFrame, numpy array, or list for initials and param_values.
Fixes: #415

Support for simulation initials, params as DataFrames

---

pysb/core.py
pysb/export/sbml.py

Not specifying any initial conditions for a species is valid SBML but the resulting model is underdetermined and simulation should fail (it actually does not, as many simulators implement a default value of `0.0`, which is also the case for libroadrunner which is used in the pysb tests). See https://github.com/sbmlteam/sbml-test-suite/issues/54

Resolve underdetermined SBML export

---

doc/installation.rst
pysb/core.py

Duplicate `Parameters` section is causing readthedocs to fail.

Documentation fixes for Sphinx

---

pysb/simulator/scipyode.py

Theano itself is "dead", so we'll remove compiler='theano' support
in a future version of ScipyOdeSimulator.

Deprecate ScipyOdeSimulator Theano backend

---

pysb/simulator/stochkit.py

I've added a custom Exception class, StochKitSimulatorException.
StochKit often has STDOUT messages that include something like:
Check log file "compile-log.txt" for error messages
The new Exception class parses the log message with a regex,
and attempts to read the log file for inclusion in the error
message. This is helpful since the log file and other temp
files are cleanup up by default.

Include StockKit log file in exceptions

---

pysb/core.py
pysb/tests/test_core.py

Currently, if one adds an invalid parameter, rule etc. that generates
an exception in `__init__`, (e.g. a validation error), the component
is still added to the model. In interactive mode, this is annoying, as
the model has to be re-instantiated. Example:
Model()
Parameter('a', 'invalid_value')  # raises ValueError
assert len(model.parameters) == 0  # fixed in this PR
Parameter('a', 1.0)  # should succeed, fixed in this PR
This PR fixes this situation by adding the Component to the Model
(by calling `Component.__init__()`) last instead of first in each
affected `__init__` method.

Stop invalid components being added to model

---

pysb/simulator/scipyode.py
pysb/tests/test_simulator_scipy.py
setup.py

This PR uses the multiprocessing module to add parallel simulation
capability to the ScipyOdeSimulator. This only works when using
Cython as a compiler.
Multiprocessing is picky about what can be pickled and sent to
child processes, so the Cython code is sent as text for use with
inline(). Since inline() is called in `__init__()` with the same code,
it utilises cython's cache, and therefore the ODEs only have to be
compiled once. The code is a little bit duplicative, since we can't
pass instance methods through to multiprocessing's processes,
thefore the `rhs()` and `jac_fn()` methods must be redefined in
each process. Requires (and checks for) Python >=3.3.

ScipyOdeSimulator multiprocessing capability

---

pysb/__init__.py
pysb/bng.py
pysb/core.py
pysb/generator/bng.py
pysb/generator/kappa.py
pysb/importers/bngl.py
pysb/tests/test_core.py
pysb/tests/test_importers.py

Duplicate sites are monomer sites with the same name. The following becomes valid PySB with this PR:
Monomer('A', ['a', 'a'])
One can then reference the sites using a tuple, with one entry
for each of the sites, for example:
A(a=(1, 2))   # Example 1
Note that this is distinct from multiple bonds to the *same* site:
A(a=[1,2])    # Example 2
In example 1, there are two sites, each named `A`, one with bond `1`
and one with bond `2`. In example 2, there is one site called `A` with
two bonds, `1` and `2`.
The syntax is similar in both cases so users will have to be careful to
check their syntax matches their use case.
Note that the data types are checked, so that expressing a
(state, bond) tuple is still valid, noting that states must be strings:
A(a=('p', 1))
Most of the refactoring in this …

Duplicate sites support

---

pysb/simulator/base.py
pysb/simulator/bng.py
pysb/tests/test_simulator_bng.py

Network free simulators use initials_dict instead of initials,
as they don't always have a full list of species available.
The Simulator class calculates the number of simulations by
checking the number of initials and parameter sets defined.
With one parameter set and multiple initials defined, only
one NFsim simulation was run (with the first set of initials).
This PR fixes this issue and adds multiple unit tests for NFsim.

Fix Simulator #sims calculation for NFsim

---

pysb/core.py
pysb/tests/test_core.py

It appears this function was non-functional and was not being tested.
This PR rectifies both.

Fix Model.update_initial_condition_pattern

---

pysb/simulator/base.py
pysb/tests/test_simulator_bng.py

The Simulator class allows users to change initials by supplying
new underlying parameter values (if both initials and params are
supplied, initials take precedence).
This behaviour was broken in the BngSimulator, which uses a dict
for initials instead of arrays, as some its simulators (e.g. NFsim)
are network free and thus may not have an exhaustive species list.
This PR fixes the issue via the initials_dict implementation,
and also refactors the initials array code to use initials_dict as well,
helping to reduce code duplication.

Fix BngSimulator when supplying initials as params

---

pysb/core.py
pysb/tests/test_core.py

This error should be raised when self exporter is used and a model
component is declared before Model(). It's broken on
Python 3.7 without this PR:
TypeError: descriptor '__init__' requires a 'ValueError' object but received a 'ModelNotDefinedError'

Fix ModelNotDefinedError

---

pysb/core.py
pysb/tests/test_core.py

Changed the code to include macros functions in the _function attribute of the Component class. This could be helpful as a way to annotate rules with the macros that generate them.

include macros functions in rule._function

---

pysb/importers/sbml.py
pysb/pathfinder.py

Atomizer now uses pysb.pathfinder to locate the external binary,
which gives a more meaningful error message.
In addition, pathfinder now shows a conda install command for missing
optional packages.
Old Error:
```
FileNotFoundError: [Errno 2] No such file or directory: '[...]/share/bionetgen/bin/sbmlTranslator': '[...]/share/bionetgen/bin/sbmlTranslator'
```
New Error:
```
Exception: The program Atomizer was not found in the default search path(s) for your operating system:
/usr/local/share/BioNetGen/bin
/Users/alex/miniconda3/envs/pysb/bin
/Users/alex/miniconda3/condabin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/TeX/texbin
/opt/X11/bin
Either install it to one of those paths, or set a custom path using the environment variable BNGPATH or by calling the function …
```

Make atomizer use pathfinder, improve help msg

---

pysb/core.py
pysb/tests/test_core.py

Use parameter and expression values (when the expression is constant) to calculate the value of a defined expression.

Evaluate expression

---

pysb/bng.py
pysb/tests/test_bng.py

Add unit test to ensure network generation and species readback from
BNG works with MultiState.

Fix MultiState species reading from BNG

---

pysb/bng.py
pysb/examples/localfunc.py
pysb/export/__init__.py
pysb/export/sbml.py
pysb/export/stochkit.py
pysb/generator/kappa.py
pysb/simulator/cupsoda.py
pysb/tests/test_examples.py
pysb/tests/test_exporters.py

* New `localfunc.py` example model, based on a BioNetGen example model
* Fix export of models with local functions to SBML and StochKit
* Show meaningful error messages when attempting to export models
with local functions to cupSODA or Kappa
* Fix local function parameter reads from BioNetGen when parameter
is actually a constant expression, e.g. `2^2`

Local function export fixes, example model

---

pysb/core.py
pysb/pattern.py
pysb/tests/test_core.py

Each bond number can connect at most two sites, otherwise an error occurs in both BNG and Kappa. This PR adds a check for this as part of the dangling bond check, during ReactionPattern instantation. E.g., the following will now generate a `ReusedBondError`:
as_reaction_pattern(A(a=1) % B(b=1) % B(b=1))
Fixes: #465

ReusedBondError when bond binds >2 sites within Complex

---

pysb/core.py
pysb/generator/bng.py
pysb/importers/bngl.py
pysb/tests/test_exporters.py

Fixes for importing BNGL models containing the following:
* Expressions referencing observables (ScipyOdeSimulator failure;
observables don't get expanded by `expand_expr()`)
* Parameters containing ^ (exponentation) (model fails to import)
This PR adds unit tests which round-trips BNGL export for PySB
example models, runs network generation, and single-steps an
integrator. These tests caught the above issues.

Fixes for BNGL importer

---

pysb/annotation.py
pysb/core.py
pysb/examples/bngwiki_egfr_simple.py
pysb/export/__init__.py
pysb/export/json.py
pysb/importers/json.py
pysb/simulator/base.py
pysb/testing/__init__.py
pysb/tests/test_exporters.py

Add JSON model import and export capabilities. JSON
is a text-serializable format, which is good for storing
models within other objects, or for purposes like HTTP
APIs.
SimulationResult.save() now saves models in JSON
rather than pickle.
See discussion on #467 which prompted the need for
a durable and serializable model storage format.

JSON model import and export

---

pysb/core.py
pysb/examples/fricker_2010_apoptosis.py
pysb/tests/test_core.py

For example, the following should cause an error, because a reverse
rate has been specified but the rule expression is not reversible:
Rule('r1', None >> A(), kf, kr)

ValueError if reverse rate specified on irreversible rule

---

.travis.yml
appveyor.yml

As per #463 and #414, the next version on PySB will remove Python 2.7 support. This PR removes Python 2.7 testing on Travis and Anaconda. Travis will test on 3.6, 3.7, and 3.8; Appveyor on 3.6 and 3.7 (3.8 not yet available by default on Appveyor).

Remove CI testing for Python 2.7, add 3.8 on Travis

---

pysb/simulator/scipyode.py
pysb/tests/test_simulator_scipy.py

Fix an error when using ScipyOdeSimulator with the num_processors
option >1 (i.e. use multiprocessing) together with compiler='python'.
Fixes #478

Fix ScipyOdeSimulator lambdify multiprocessing

---

pysb/core.py
pysb/generator/bng.py
pysb/macros.py
pysb/pattern.py
pysb/tests/test_importers.py

`super(sympy.Symbol, cls).__new__` calls `sympy.Basic.__new__`, not `sympy.Symbol.__new__`

fix usage of super in multiple inheritance of sympy.Symbol

---

.travis.yml
appveyor.yml
doc/conf.py
doc/examples/robertson_standalone.py
doc/faq.rst
doc/installation.rst
pysb/export/python.py
pysb/simulator/scipyode.py
pysb/tests/test_exporters.py
pysb/tests/test_simulator_scipy.py
setup.py

Remove legacy weave and theano support from ScipyOdeSimulator.
The Python exporter has also been updated to use Cython
rather than weave.

Remove weave and theano from ScipyOdeSimulator

---

pysb/simulator/base.py

According to [h5py](https://h5py.readthedocs.io/en/stable/high/dataset.html#reading-writing-data):  Slice specifications are translated directly to HDF5 “hyperslab” selections, and are a fast and efficient way to access data in the file.
PySB currently passes the `trajectories` h5py Dataset object to the `SimulationResult` object. Then, it iterates over the trajectories. This iteration is slow because it uses the Dataset` __iter__` method. If we access the data first (which it already returns a numpy.array) and iterate over these objects, loading the simulations become faster.
Some benchmarks:
```python
from pysb.simulator import SimulationResult, ScipyOdeSimulator
from pysb.examples.tyson_oscillator import model
import numpy as np
tspan = np.linspace(0, 100, 100)
pars = np.array([p.value …
```

Faster SimulationResult loading: use slices

---

pysb/bng.py
pysb/core.py
pysb/export/json.py
pysb/tests/test_simulator_scipy.py

Fixes an issue when a model with local functions is used
with the ScipyOdeSimulator eqn_mode='python'. Lambdify would
show a NameError and wouldn't pick up model parameters, due to
those not being referenced when local functions are read back
in from BNG during network generation.
Includes a unit test as an example.
**Also:** I had to fix a second issue to get tests to pass:
PySB currently prints expressions consisting of one
parameter or expression like so:
Expression('e', Parameter('p', 1.0))
Whereas, for consistency, export etc., it should be:
Expression('e', p)

Fix eqn_mode='python' with local fxns

---

pysb/core.py
pysb/tests/test_core.py

Currently, patterns like `None | A()` are not recognised, although they
work if one reverses the order. This PR fixes reversible synthesis
rules like this, and adds some tests.

Implement reversible synthesis rules

---

pysb/export/json.py
pysb/importers/json.py
pysb/tests/test_exporters.py
pysb/tests/test_simulationresult.py

When loading a SimulationResult from an HDF5 file using the .load()
method, observables are left as zeroes (if the observables were not
saved with the results using the include_obs_exprs=True argument).
The issue is due to the fact that Observable species and coefficients
are not saved in the JSON representation, despite the
include_netgen=True argument. This was missed due to a typo in the
SimulationResult unit tests, also fixed here.
This PR addresses the issue by calculating the Observable species
and coefficients using PySB's built-in pattern matching during
the JSON import process. This approach allows existing HDF5 files
to be used without resaving.

Fix observable trajectories on HDF5 load

---

pysb/bng.py
pysb/importers/bngl.py
pysb/tests/test_bng.py

BNG treats booleans as integers within expressions (1=True,
0=False), so an expression like `(2 > 1) * 4` will get evaluated
to `4`. Sometimes these expressions get produced by BNG
local functions and may be present in other imported models as
well. However, doesn't implement multiplication of
BooleanAtoms, which causes a TypeError.
This PR implements the BNG style behaviour on import by
patching BooleanTrue.__mul__ and BooleanFalse.__mul__.
Not very elegant, but it works.

Implement BNG boolean treatment within expressions

---

pysb/core.py

see https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values

fix typehints PEP0484

---

pysb/export/stochkit.py

Reactions with a rate as a PySB Expression object
(rather than merely containing one) are exported to StochKit 
by string conversion, which renders like "Expression(...)".
This PR detects and fixes this case.

Fix StochKit export of certain PySB rxn Expressions

---

pysb/simulator/cupsoda.py

to use to_numpy() due to .as_matrix() being deprecated. Based on @glucksfall issue #514

Updating cupsoda.py 

---

pysb/core.py
pysb/tests/test_core.py

Previously, only parameters were allowed for compartment sizes.
This change allows specifying compartment sizes using constant expressions.
Closes pysb/pysb#524

Allow constant expressions for compartment sizes

---

pysb/generator/bng.py
pysb/tests/test_bng.py

Previously, Eq generated `Eq(...)` instead of `==`, and similarly for Ne.
This changes them to generate `==` and `!=`, as BNGL (muparser) expects.
The code is copied and simplified from StrPrinter's _print_Relational
implementation.

Fix BNG code generation for Eq and Ne

---

pysb/core.py
pysb/examples/run_earm_1_0.py
pysb/logging.py
pysb/simulator/base.py
pysb/simulator/scipyode.py
pysb/tests/test_simulator_scipy.py
setup.py

This moves all codegen out of the simulator class. A new abstract class
RhsBuilder is introduced to manage codegen, and Python and Cython concrete
implementations are provided. The codegen itself is now performed using sympy
expression manipulation and sympy's own codegen rather than hand-rolled string
manipulations and Cython.inline. Performance is improved since Cython.inline's
overhead on long code strings was really hurting us.

Scipyode simulator refactor

---

pysb/tests/test_simulationresult.py

In test_simulationresult, a warnings filter is used which got
triggered by a DeprecationWarning in new versions of h5py (3.1.0).
This PR updates the filter to only catch UserWarnings; other
warning types will now be emitted normally.

Fix DeprecationWarning leading to test failure

---

pysb/tools/sensitivity_analysis.py

Specifically, accepted values for the `whis` argument to
matplotlib.pyplot.boxplot no longer includes the string literal
'range'. Instead, supply a tuple `(0, 100)`, indicating the same
thing with percentiles.

Fix altered matplotlib API call

---

doc/modules/index.rst
doc/modules/pathfinder.rst
pysb/pathfinder.py
pysb/tests/test_pathfinder.py

Also add a new function pysb.pathfinder.list_programs() to discover
available external programs and their environment variables at
runtime, and some tests.

Add pysb.pathfinder to documentation

---

doc/faq.rst

Python throws SyntaxError in the example code in FAQ page:
```python
Expression('kf_A`, A_total * A_multiplier)
^
```                                         
> SyntaxError: EOL while scanning string literal
↓
```python
Expression('kf_A', A_total * A_multiplier)
```

Fix SyntaxError in FAQ

---

.travis.yml

Conda-installed `h5py` is currently failing on Travis using Python 3.7 and 3.8:
```
$ python -c "import h5py"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/travis/miniconda/lib/python3.7/site-packages/h5py/__init__.py", line 33, in <module>
from . import version
File "/home/travis/miniconda/lib/python3.7/site-packages/h5py/version.py", line 15, in <module>
from . import h5 as _h5
File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /home/travis/miniconda/lib/python3.7/site-packages/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
```
This PR works around the issue by using pip-installed `h5py` rather than the conda-installed one.

Fix travis h5py issue

---

pysb/simulator/base.py

Numpy v1.24 deprecated ragged arrays unless dtype=object is passed (numpy/numpy#22004). The SimulationResult class needs to support different length entries in tout in the case these differ across simulations. PySB shouldn't convert these to a numpy array, instead preferring to keep them as a list/iterable, which avoids causing an error with Numpy v1.24 when running the PySB test suite.

Fix numpy v1.24 compatibility

---

.github/workflows/ci.yml

This lets us see all the possible problems across the entire CI matrix rather than cancelling all the jobs as soon as any one fails.

Disable GitHub Actions fail-fast

---

.github/pysb-conda-env.yml
pysb/tests/test_importers.py

Two CI failures have crept in with updates to BNG and NFsim.
This first is an error simulating a hybrid particle-population model in our test suite. This looks like a bug in NFsim 1.14.1, which generates a segfault on the model which worked in 1.12.1. I've opened an issue with NFsim for this here:
https://github.com/RuleWorld/nfsim/issues/37
In the meantime, I've pinned the test suite GitHub Actions CI to NFsim 1.12.1.
The other is a test failure in a BNG model import, which looks like it's just a consequence of the rule order parsing changing between BNG versions. I've updated the test to test for the presence of either of the two expected error messages, both regarding rate laws.

fix: CI failures with updated BNG/NFsim

---

pysb/anneal_mod.py

Numpy 2.0 was just released and I'm going over some repos to see if there are any incompatibilities. I found a couple of minor changes needed here to be compatible with the new version per https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide.

Adapt to numpy 2.0

---

.github/workflows/ci.yml

Mostly straightforward changes to the matrix `os` entry to get the guaranteed arm64 runner with `macos-14`. I think since I started this work, `macos-latest` is now arm64, but sticking with `macos-14` for now seems fine.
I needed to rework how stochkit presence/absence is handled since it no longer works on macOS at all (no arm64 stochkit build). My solution sets an environment variable in the steps that install stochkit, then checks that variable in the actual nosetests step to conditionally exclude stochkit tests. I needed to use the nosetests `--exclude` option because that's the only way to also skip specific doctests (there's no way to apply the `-a` attrs to doctests).
I also updated some action versions while I was editing the workflow.

Switch MacOS CI runner to ARM
