pysb/pysb

pysb/core.py, pysb/tests/test_core.py
Also add a test for ComplexPattern.__call__ behavior. @johnbachman Let's review this and the other outstanding PRs soon.
=> Add conditions arg to ComplexPattern.__call__

.gitignore, .travis.yml, pysb/bng.py, pysb/integrate.py, pysb/tools/species_graph.py
Rebased #150 against master rather than merging from it.
=> Add coveralls.io support, BioNetGen 2.2.6 to travis, lsoda wrapper cleanup

pysb/bng.py, pysb/tests/test_bng.py
this resolves a problem we were having with render_reactions.
=> fixed a bug in the creation of bidirectional reactions.

pysb/core.py, pysb/export/__init__.py, pysb/export/pysb_flat.py, pysb/export/python.py, pysb/macros.py
This exporter produces a single .py source file that acts as a "repr" for a whole model. Fixes #173.
=> Add pysb_flat exporter

pysb/export/pysb_flat.py
Annotations were not exported before.
=> Print model annotations in pysb_flat export

doc/conf.py, doc/requirements.txt
The readthedocs build has been broken for a while for various reasons. These
changes will fix it.
=> Sphinx / ReadTheDocs fixes

pysb/examples/run_tyson_oscillator.py
These removes the comments from the file as requested in  #142
=> Removed comments from run_tyson_oscillator

.travis.yml
=> Add aspcud to .travis.yml to fix opam error

pysb/simulator/stochkit.py
Fix sphinx docs by adding blank lines around examples.
=> Fix sphinx examples for StochKitSimulator

doc/tutorial.rst
Minimal changes to get tutorial examples working.
=> Fix refs to ScipyOdeSimulator in tutorial

pysb/bng.py
There were a couple of try/catch blocks that in pysb/bng.py that were
capturing `Exception`s and recasting them as `BngInterfaceError`.
Sometimes this masks genuine errors, particularly on Python 2
(which doesn't chain exceptions). This PR removes these blocks.
We should reserve `BngInterfaceError` for cases where BNG returns
an error, or where PySB has identified an issue which precludes
compatibility with BNG.
=> Avoid recasting Exceptions in BNG interface

pysb/core.py, pysb/tests/test_core.py
=> Fix component rename on non-SelfExported model

pysb/core.py, pysb/tests/test_core.py
=> Fixes and tests for ComplexPattern.is_concrete()

pysb/simulator/cupsoda.py
CupSodaSimulator was erroring on the models with rates consisting
of a single Parameter or Expression. Calling .args on these returns
a string, not a pysb.Component object, which fails when we try to
multiply together to get the rate. This commit introduces a check
and workaround in the CupSodaSimulator.
I've also removed the pycuda.autoinit import, which triggers GPU
initialization when pysb.simulator is imported, even if a
CupSodaSimulator is not instantiated. Instead, pycuda is initialized
on demand within the n_blocks function.
=> Fix cupsoda simulator error on Tyson model

doc/faq.rst, doc/index.rst
I've added some initial FAQs to the documentation, which we can build off of over time.
Based off of PR #329.
=> Add Frequently Asked Questions to docs

pysb/annotation.py, pysb/examples/fricker_2010_apoptosis.py, pysb/export/python.py, pysb/tests/test_exporters.py
* Python 3 compatibility in Python exporter
* Unit tests for Python and PySB flat exporters
* A few small fixes to get the tests running
=> Fix Python and PySB flat exporters, add tests

.travis.yml
Now that Python 3.7 has been released, we should add it to our tests.
=> Test on Python 3.7 on Travis

pysb/importers/bngl.py
=> Allow relative paths in BNGL importer

pysb/examples/run_bax_pore.py, pysb/examples/run_bax_pore_sequential.py, pysb/examples/run_earm_1_0.py, pysb/examples/run_earm_hpp.py, pysb/examples/run_earm_stochkit.py, pysb/examples/run_fixed_initial.py, pysb/examples/run_kinase_cascade.py, pysb/examples/run_robertson.py, pysb/examples/run_tyson_oscillator_stochkit.py
=> Remove shebang, exec bits on run_*.py examples

pysb/core.py
=> Remove commented-out expressions_constant in core

.travis.yml
Pre-built package should reduce Travis build time
=> Travis: use anaconda libsbml pkg on Py3.7

pysb/simulator/scipyode.py
Currently, PySB uses the concurrent.futures submit function for multiprocessing. This submit function adds the simulation function to a queue that is then accessed by a process worker. When we try to simulate large numbers (~10 000) of initial conditions or parameter values, the simulation takes a long time to finish. After digging into the python multiprocessing code, I think that the problem arises from having too many elements in the queue, which makes it slower for the workers to get() _CallItems and put() the simulation results in the result_queue queue. Using map would fix this as it divides the parameter values or initial conditions into different chunks that are then submitted to a queue, thus reducing the number of elements in a queue (although they have a larger size).
**Some …
=> ScipyOdeSimulator speedup through use of partial

pysb/bng.py, pysb/core.py, pysb/importers/json.py, pysb/pattern.py, pysb/simulator/base.py, pysb/simulator/bng.py, pysb/simulator/cupsoda.py
=> Import ABC from collections.abc instead of collections for Python 3.9 compatibility.

pysb/bng.py, pysb/macros.py
Fix incompatibility with sympy 1.6 due to deprecation of string sympification
=> Fix Sympy 1.6 Incompatibility

doc/tutorial.rst
Hi there! 
Here are some suggestions to fix typos in the tutorial.
=> Fixing typos

pysb/bng.py
Changed sympy.boolalg to sympy.logic.boolalg. Also removed unused imports.
=> Fix deprecated usage of sympy.boolalg

pysb/core.py
Add an extended description of MatchOnce with a
worked example to the docstring.
=> Improve documentation on MatchOnce keyword

pysb/core.py, pysb/generator/bng.py, pysb/tests/test_bng.py
Hi, I had sent a pull request for this functionality a few years back (https://github.com/pysb/pysb/pull/304). I have now addressed the reviewer comment (https://github.com/pysb/pysb/pull/304#issuecomment-336250126). Let me know if you would like any further edits for this to be merged with master. Thanks!
=> Add total_rate option to rules for NFsim compatibility

.github/pysb-conda-env.yml, doc/requirements.txt, setup.py
Pin sympy<1.12 and sphinx<7 to avoid breaking changes.
=> Dependency pins for sympy and sphinx

pysb/__init__.py, pysb/bng.py, pysb/core.py, pysb/examples/time.py, pysb/export/pysb_flat.py, pysb/export/sbml.py, pysb/export/stochkit.py, pysb/generator/bng.py, pysb/generator/kappa.py, pysb/importers/bngl.py, pysb/macros.py, pysb/simulator/base.py, pysb/simulator/scipyode.py, pysb/simulator/ssa_base.py, pysb/tests/test_exporters.py, pysb/tests/test_integrate.py, pysb/tests/test_simulator_scipy.py
=> Support for explicit time dependency in expressions
